-- AlterTable
ALTER TABLE "public"."Document" ADD COLUMN     "totalFeePrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalMaterialPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
